project_id = "supiwygxypfqjzoqmlaq"

[functions.midtrans-order-settings]
verify_jwt = false

[functions.midtrans-order-charge]
verify_jwt = false

[functions.midtrans-webhook]
verify_jwt = false

[functions.super-admin-midtrans-payments]
verify_jwt = false

[functions.super-admin-xendit-secret]
verify_jwt = false